name: scrabble_P2P
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  network_info_plus: ^5.0.3
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.3.0
  http: ^1.2.0
  logger: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo/app_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
